package globals

const (
	MESSAGE_TYPE_GAME_STATUS           = "GAME_STATUS"
	MESSAGE_TYPE_PLAYER_CREATED        = "PLAYER_CREATED"
	MESSAGE_TYPE_START_GAME            = "START_GAME"
	MESSAGE_TYPE_UPDATE_DRAWING_PLAYER = "UPDATE_DRAWING_PLAYER"
	MESSAGE_TYPE_PLAYER_WORD_OPTIONS   = "CHOOSE_WORD"
	/*
		These are messages that are sent to users releated to the game
	*/
	MESSAGE_TYPE_GAME_MESSAGE        = "GAME_MESSAGE"
	MESSAGE_TYPE_PLAYER_CHOOSED_WORD = "CHOOSED_WORD"
	MESSAGE_TYPE_GAME_WORD_CLUE      = "GAME_WORD_CLUE"
	MESSAGE_TYPE_DRAW                = "DRAW"
	MESSAGE_TYPE_STREAM_DRAW         = "STREAM_DRAW"
	MESSAGE_TYPE_CHAT                = "CHAT"
	MESSAGE_TYPE_GAME_CHAT           = "GAME_CHAT"
	/*
		This message type is basically when the system(game) needs to send messages to its players
	*/
	MESSAGE_TYPE_ADMIN_INFO = "ADMIN_MESSAGE"
)

const (
	GAME_STATUS_IDLE    = "IDLE"
	GAME_STATUS_STARTED = "STARTED"
)

const (
	MESSAGE_TYPE_ROOM_CREATION = "ROOM_CREATION"
)

const (
	MESSAGE_SENDER_ADMIN = "ADMIN"
)
